### PR TITLE
Upgrade to the latest Vault

### PR DESCRIPTION
**Pull request by ryanwohara**
We are updating the latest Vault
available in Docker Hub in an
effort to patch sqlite-libs.

### CODE REVIEW

**Comment by conormcd** [comment]
Is this the same version of Vault we use in Cloud? If not, we should check the changelog for Vault to ensure that we don't expose ourselves to Cloud v Server bugs.

**Comment by ryanwohara** [comment]
The changelog appears to only have bug fixes and no breaking changes https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#113-june-5th-2019
Looking into the cloud version

**Comment by conormcd** [comment]
@ryanwohara Did we find out about the Cloud version of Vault?

**Comment by ryanwohara** [comment]
@conormcd No, and I believe @tito-villalobos is leading this effort now.

**Pull request closed without merging**
